### ISSUE TITLE
leading blank line in pom.xml causes mvn to fail

### ISSUE THREAD

**Issue by heapifyman** [vineetsemwal/quickview#1]
The leading blank line in quickview/quickview/pom.xml causes maven to fail on some systems with the error message at the bottom. If you remove the blank line all will be fine.

Happened with the following setup:
Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Java version: 1.6.0_33, vendor: Sun Microsystems Inc.
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

Error message:
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (C:\quickview\quickview\pom.xml) has 1 error
[ERROR]     Non-parseable POM C:\quickview\quickview\pom.xml: processing instruction can not have PITarget with reservel
d xml name (position: START_DOCUMENT seen \r\n<?xml ... @2:7)  @ line 2, column 7 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**Comment by musicalFOX** [comment]
what the..........
