### ISSUE TITLE
Could you publish it in Maven central?

### ISSUE THREAD

**Issue by vershinin** [vineetsemwal/quickview#21]
Hi!
It would be nice, if this library will be published in central repo.

**Comment by vineetsemwal** [comment]
Hi,
Sorry for an extremely late reply,this project has moved to wicketstuff and will therefore see a release with every new wicket version from 8.3.0
there are few package changes and few improvements,way of doing things is same.

Dependency for maven project is 
<dependency>
        <groupId>org.wicketstuff</groupId>
        <artifactId>quickview</artifactId>
        <version> 8.3.0 </version>
    </dependency>

Thank you ,
Regards
