### ISSUE TITLE
Release containing last fixes

### ISSUE THREAD

**Issue by bartoszsroka** [vineetsemwal/quickview#24]
Can you prepare a release containing fixes done in following commit: https://github.com/vineetsemwal/quickview/commit/b0305f6e347e325c707bed41a4d5413cdbb557f8 ?

**Comment by vineetsemwal** [comment]
Hi,
I just created tag wicket-quickview-6.16.0 for 6.x branch,it contains the fix you mentioned,the tag for the master which is on 7.x will be created as soon as the wicket team creates their new release for 7.x
